# WhatATheme
markdown: kramdown

# URL of the Site
url: ""
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Home of Derican
# Description of the Site
description: A simple blog for Derican
# URL of Image of the Site
site-image:
# Keywords of the Site
site-keywords:
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/desktop.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: derican112@outlook.com
facebook_username: Derican
twitter_username: derican1
instagram_username:
linkedin_username:
github_username: derican
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:
bilibili_uid: 36858475

# Google Analytics
google-analytics: G-MMGWFQWS2K

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Derican
# URL for the Image of the Author
author-image: /
# 60 Words About the Author
author-about: An undergraduate from Tsinghua University.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/derican

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"
permalink: "cv/"
permalink: "category/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page
  - scope:
      type: "categories"
    values:
      layout: category-post

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
